### ISSUE TITLE
Enabling/Disabling the site setting requires a restart of the app to take effect.

### ISSUE THREAD

**Issue by tgxworld** [JafethDC/discourse-user-feedback#2]
Relevant line of code: https://github.com/JafethDC/discourse-user-feedback/blob/ba315720ce4c710b4b448262b17c6113e98a6481/plugin.rb#L32

**Comment by jafethdc** [comment]
Hmmm I understand, that line is practically unnecessary, right? :sweat_smile:

**Comment by tgxworld** [comment]
You should add a check in the serializer to check if it should include those attributes based on whether the plugin is enabled.

**Comment by jafethdc** [comment]
Got it. I will modify my `add_to_serializer` calls to have the `define_include_method` parameter as true, so that the serializer performs the check.

**Comment by tgxworld** [comment]
Yup :+1:
